name: CI
on: [push]
jobs:
  build:
    name: Build and Test Project before use.

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

        uses: bahmutov/npm-install@v1

      - name: Running Lint
        run: npm run lint

      - name: Running Test
        run: npm run test --ci --coverage --maxWorkers=2
